---
abstract: 'Make serving static pages painless.'
author:
  - 'Andy Grundman, <andy@hybridized.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Static-Simple
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.80008
  MIME::Types: 1.25
  Moose: 0
  MooseX::Types: 0
  Test::More: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Plugin-Static-Simple/trunk/
version: 0.28
